# Generated by Django 2.0b1 on 2019-01-27 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GbMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('standard', models.CharField(blank=True, max_length=32, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.GbMethod')),
            ],
        ),
        migrations.CreateModel(
            name='GbPerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=64, unique=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('seq', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField(choices=[(0, '/'), (1, '委托检验'), (2, '未确定')])),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('prod_date', models.DateTimeField(blank=True, null=True)),
                ('spec', models.CharField(blank=True, max_length=32, null=True)),
                ('num', models.CharField(max_length=32)),
                ('store', models.CharField(max_length=64)),
                ('prop', models.IntegerField(choices=[(0, '/'), (10, '固态/散装'), (11, '固态/棉纸装'), (12, '固态/罐装'), (21, '液态/无菌生理盐水试管'), (22, '液态/瓶装'), (23, '液态/罐装'), (24, '液态/无菌瓶'), (31, '固液混合态/瓶装')])),
                ('source', models.CharField(max_length=64)),
                ('prod_firm', models.CharField(blank=True, max_length=64, null=True)),
                ('agent_firm', models.CharField(blank=True, max_length=64, null=True)),
                ('agent_address', models.CharField(blank=True, max_length=128, null=True)),
                ('agent_user', models.CharField(max_length=32)),
                ('agent_tell', models.CharField(max_length=32)),
                ('accept_firm', models.CharField(blank=True, max_length=64, null=True)),
                ('accept_user', models.CharField(max_length=32)),
                ('accept_tell', models.CharField(max_length=32)),
                ('send_user', models.CharField(max_length=32)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('rec_user', models.CharField(max_length=32)),
                ('rec_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, '已收样'), (1, '已生成流转单'), (2, '已生成报告'), (3, '已发放报告'), (9, '已删除')], default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('state_time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_start_date', models.DateTimeField(auto_now_add=True)),
                ('check_end_date', models.DateTimeField(blank=True, null=True)),
                ('temperature_start', models.CharField(blank=True, max_length=32, null=True)),
                ('temperature_end', models.CharField(blank=True, max_length=32, null=True)),
                ('humidity_start', models.CharField(blank=True, max_length=32, null=True)),
                ('humidity_end', models.CharField(blank=True, max_length=32, null=True)),
                ('instrument', models.CharField(max_length=128)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('perform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheet', to='api.GbPerform')),
                ('sample', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sheet', to='api.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='SheetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('parent', models.CharField(blank=True, max_length=64, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('standard', models.CharField(blank=True, max_length=32, null=True)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Sheet')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='sample',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.Sample'),
        ),
        migrations.AddField(
            model_name='gbmethod',
            name='perform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='api.GbPerform'),
        ),
    ]
