# Generated by Django 2.0b1 on 2019-01-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='sample',
        ),
        migrations.AddField(
            model_name='sample',
            name='report',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='api.Report'),
        ),
    ]
