# Generated by Django 2.0b1 on 2019-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190127_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetitem',
            name='conclusion',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
